// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query_complex.sql

package complex_example

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
insert into User(email, gpa) values (?, ?)
`

type CreateUserParams struct {
	Email string
	Gpa   float64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Email, arg.Gpa)
	return err
}
