// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package simple_example

import (
	"database/sql"
)

type Author struct {
	ID    int64
	Name  string
	Age   sql.NullInt64
	Alive int64
}

type Book struct {
	ID       int64
	Authorid int64
	Name     string
}
