// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query_simple.sql

package simple_example

import (
	"context"
)

const createAuthor = `-- name: CreateAuthor :exec
insert into Author(id, name) values (?, ?)
`

type CreateAuthorParams struct {
	ID   int64
	Name string
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) error {
	_, err := q.db.ExecContext(ctx, createAuthor, arg.ID, arg.Name)
	return err
}
